language: node_js

node_js:
 - "stable"

services:
 - MongoDB

install:
 - npm ci

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});

script:
 - npm test
 - npm run build

deploy:
 provider: heroku 
 skip_cleanup: true
 api_key: $herokuKEY
 on:
  branch: TravisAddition
 

