language: node_js
node_js:
 - "stable"
cache:

install:
 - npm ci

script:
 - npm test
 - npm run build

deploy:
 provider: heroku 
 skip_cleanup: true
 api_key: $herokuKEY
 on:
  branch: TravisAddition
 

