language: node_js

node_js:
 - "stable"

services:
 - MongoDB

install:
 - npm ci

script:
 - npm test
 - npm run build

deploy:
 provider: heroku 
 skip_cleanup: true
 api_key: $herokuKEY
 on:
  branch: TravisAddition
 

