language: node_js
node_js:
 - "stable"
cache:
 directories:
 - node_modules
script:
 - npm test
 - npm run build
deploy:
 provider: heroku 
 skip_cleanup: true
 api_key: 53627007-54bd-4fdb-835e-10bef26e6edf
 on: TravisAddition
 

