language: node_js

node_js:
 - "stable"

cache: npm

services:
 - MongoDB

script:
  - echo '***build starting***'
  - echo 'installing dependencies'
  - npm install
  - echo 'running test'
  - mocha

deploy:
 provider: heroku 
 skip_cleanup: true
 api_key: $herokuKEY
 on:
  branch: TravisAddition
 

