language: node_js

node_js:
 - "stable"
 - "6"
 - "7"
 - "5"

cache: npm

services:
 - MongoDB

script:
  - echo '***build starting***'
  - echo 'installing dependencies'
  - npm install
  - echo 'running test'
  - mocha


